# Generated by Django 2.2.18 on 2021-12-13 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aloqa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=300)),
                ('massage', models.TextField(default=0)),
            ],
            options={
                'verbose_name': 'Aloqa',
                'verbose_name_plural': 'Aloqalar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'Categorya',
                'verbose_name_plural': 'Categoryalar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Kiyimlar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('content', models.TextField(default='')),
                ('image', models.ImageField(upload_to='')),
                ('size', models.IntegerField(default=0)),
                ('number', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='category', to='habibi.Category')),
            ],
            options={
                'verbose_name': 'Kiyim',
                'verbose_name_plural': 'Kiyimlar',
                'ordering': ['name'],
            },
        ),
    ]
