# Generated by Django 3.2.8 on 2021-11-23 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habibi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kiyimlar',
            options={'ordering': ['name'], 'verbose_name': 'Kiyim', 'verbose_name_plural': 'Kiyimlar'},
        ),
        migrations.RemoveField(
            model_name='kiyimlar',
            name='link',
        ),
    ]
