# Generated by Django 3.2.9 on 2021-12-01 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habibi', '0002_aloqa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aloqa',
            options={'ordering': ['name'], 'verbose_name': 'Aloqa', 'verbose_name_plural': 'Aloqalar'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Categorya', 'verbose_name_plural': 'Categoryalar'},
        ),
    ]
