# Generated by Django 3.2.8 on 2021-11-23 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habibi', '0002_auto_20211123_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='kiyimlar',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='kiyimlar',
            name='number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kiyimlar',
            name='size',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='kiyimlar',
            name='name',
            field=models.CharField(default='default title', max_length=100),
        ),
    ]
