# Generated by Django 3.2.8 on 2021-11-23 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habibi', '0003_auto_20211123_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kiyimlar',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
