# Generated by Django 3.2.8 on 2021-11-24 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('habibi', '0006_remove_kiyimlar_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='kiyimlar',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='category', to='habibi.category'),
            preserve_default=False,
        ),
    ]
